#
# Module manifest for module 'ConditionalAccessAnalyzer'
#
# Generated by: Gregory Hall
#
# Generated on: April 6, 2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'ConditionalAccessAnalyzer.psm1'
    
    # Version number of this module.
    ModuleVersion = '1.0.0'
    
    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')
    
    # ID used to uniquely identify this module
    GUID = '32e12c99-f45c-4b34-9bc7-d5a76af8e365'
    
    # Author of this module
    Author = 'Gregory Hall'
    
    # Company or vendor of this module
    CompanyName = 'DataGuys'
    
    # Copyright statement for this module
    Copyright = '(c) 2025 Gregory Hall. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'A comprehensive PowerShell module for analyzing Conditional Access policies in Microsoft Entra ID (Azure AD). This module evaluates CA configurations against Zero Trust security best practices including MFA enforcement, device compliance, risk-based access, and data protection controls.'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        @{ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '1.20.0'},
        @{ModuleName = 'Microsoft.Graph.Identity.SignIns'; ModuleVersion = '1.20.0'},
        @{ModuleName = 'Microsoft.Graph.Identity.DirectoryManagement'; ModuleVersion = '1.20.0'},
        @{ModuleName = 'Microsoft.Graph.DeviceManagement'; ModuleVersion = '1.20.0'}
    )
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Connect-CAAnalyzer',
        'Get-CAPoliciesSummary',
        'Test-AdminMFARequired',
        'Test-UserMFARequired',
        'Test-DeviceComplianceRequired',
        'Test-TokenSessionBinding',
        'Test-RiskBasedPolicies',
        'Test-MAMPolicies',
        'Test-ZeroTrustNetwork',
        'Invoke-CAComplianceCheck',
        'Export-CAComplianceReport',
        'New-CABestPracticePolicy'
    )
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('ConditionalAccess', 'Security', 'Entra', 'AzureAD', 'ZeroTrust', 'MFA', 'ComplianceCheck')
            
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/DataGuys/ConditionalAccess/blob/main/LICENSE'
            
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/DataGuys/ConditionalAccess'
            
            # ReleaseNotes of this module
            ReleaseNotes = '
            1.0.0 - Initial release with comprehensive Conditional Access policy analysis capabilities
            - MFA enforcement analysis for admins and regular users
            - Device compliance validation 
            - Token session binding checks
            - Risk-based policy evaluation
            - Mobile Application Management policy detection
            - Zero Trust Network Access checks
            - HTML, CSV, and JSON reporting
            '
        }
    }
}
